### ISSUE TITLE
How can I obtain image features for my own dataset?

### ISSUE THREAD

**Issue by Fuzesunshine** [YIKUAN8/Transformers-VQA#1]

**Comment by yikuan8** [comment]
[Bottom-up attention](https://github.com/peteanderson80/bottom-up-attention) is the conventional method to extract visual features. 
I also recommend this pytorch [implementation](https://github.com/airsplay/py-bottom-up-attention) which is easier to set it up.

**Comment by Fuzesunshine** [comment]
> [Bottom-up attention](https://github.com/peteanderson80/bottom-up-attention) is the conventional method to extract visual features.
> I also recommend this pytorch [implementation](https://github.com/airsplay/py-bottom-up-attention) which is easier to set it up.

**Comment by Fuzesunshine** [comment]
It's very helpful, thx a lot~
