### ISSUE TITLE
Code for training on MIMIC data

### ISSUE THREAD

**Issue by jwaldor** [YIKUAN8/Transformers-VQA#10]
I'm interested in training V+L models on MIMIC data. Do you have the code that you used to train V+L models on MIMIC data for the paper "A Comparison of Pre-trained Vision-and-Language Models for Multimodal Representation Learning across Medical Images and Reports"? Thank you.

**Comment by yikuan8** [comment]
Please refer to the Google Colab link which is an example of training on OpenI.
