### ISSUE TITLE
will you release the code for pixel-bert?

### ISSUE THREAD

**Issue by tjulyz** [YIKUAN8/Transformers-VQA#2]

**Comment by yikuan8** [comment]
Yes, stay tuned. I will release the code once the authors of pixel-bert release their pre-trained weight.

**Comment by fengxin619** [comment]
> Yes, stay tuned. I will release the code once the authors of pixel-bert release their pre-trained weight.

haha, look forward to seeing your code。。

**Comment by yikuan8** [comment]
The corresponding author of pixel-bert is an acquaintance of my advisor. We won't take their credit for the implementation of pixel-bert. Given that they don't have a plan of publishing their implementation on Github, neither will we at this point.

**Comment by guanhdrmq** [comment]
Hi 
When would you release pixel-bert code and pre-trained model？
Thanks
