### ISSUE TITLE
Can't download files from nlp1.cs.unc.edu websites

### ISSUE THREAD

**Issue by maximek3** [YIKUAN8/Transformers-VQA#4]
Hey, thanks a lot for this repo. I am not managing to download any of the dataset or feature files from any of the addresses that start with https://nlp1.cs.unc.edu/. Do you know why this could be? Thank you.

The error message I get is this: `Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.`

**Comment by yikuan8** [comment]
Hey there,

I copied those addresses from the repo of [lxmert](https://github.com/airsplay/lxmert). It seems like they experienced an URL broken recently. Please refer to their repo for the updated addresses. I will also keep it update sooner than later.

**Comment by maximek3** [comment]
Cheers, thanks!

**Comment by yikuan8** [comment]
Hey there, URLs for LXMERT are updated.

**Comment by maximek3** [comment]
Cheers, thanks!
