### ISSUE TITLE
Comparison of speed of extracting features?

### ISSUE THREAD

**Issue by yezhengli-Mr9** [YIKUAN8/Transformers-VQA#5]
Hi @YIKUAN8, @HanyinWang, @yuanluo,
Is there any rough comparison of speed of extracting features, for [VisualBERT](https://github.com/uclanlp/visualbert/), [LXMERT](https://github.com/airsplay/lxmert), and [UNITER](https://github.com/ChenRocks/UNITER)?  Not appeared in [1]. 

-  I have to handle 1,102,076+ personal images and have to find a fast one even the performance might be lower -- it is fine NOT to be any of [VisualBERT](https://github.com/uclanlp/visualbert/), [LXMERT](https://github.com/airsplay/lxmert), and [UNITER](https://github.com/ChenRocks/UNITER), but **better faster to implement**.

For example, by comparison with one GPU (cpu-only is presumably [not tolerable](https://github.com/airsplay/lxmert/issues/89)), for NLVR2 107,292 images,  [lxmert](https://github.com/airsplay/lxmert) takes 5-6 hours to extract faster-rcnn features by [this caffe](https://github.com/peteanderson80/bottom-up-attention/tree/master/caffe).

I am checking #1. I also follow [this issue in VisualBERT](https://github.com/uclanlp/visualbert/issues/10).

[1] [A Comparison of Pre-trained Vision-and-Language Models for Multimodal Representation Learning across Medical Images and Reports](https://arxiv.org/pdf/2009.01523.pdf).

**Comment by yikuan8** [comment]
Hello Yezheng,

Thank you for your question. VisualBERT, LXMERT, and UNITER all adopt the same visual feature extraction algorithm (BUTD). It is a one-time investment that is hard to avoid. Should I recall correctly, we spent roughly 4 days on this step without any GPU support for ~ 200,000 CXR images. PixelBERT does save time on visual feature extraction. However, the pre-trained weights haven't released. 

In terms of the time expense for down-streaming, those 3 models are almost the same, as they all have 12 BertLayers.

Please let me know should you have any further questions. Please star our repo/cite our work if you think it is helpful:)

**Comment by yezhengli-Mr9** [comment]
> Hello Yezheng,
> 
> Thank you for your question. VisualBERT, LXMERT, and UNITER all adopt the same visual feature extraction algorithm (BUTD). It is a one-time investment that is hard to avoid. Should I recall correctly, we spent roughly 4 days on this step without any GPU support for ~ 200,000 CXR images. PixelBERT does save time on visual feature extraction. However, the pre-trained weights haven't released.
> 
> In terms of the time expense for down-streaming, those 3 models are almost the same, as they all have 12 BertLayers.
> 
> Please let me know should you have any further questions. Please star our repo/cite our work if you think it is helpful:)

@YIKUAN8 , this makes sense.  Thanks a lot~ I think I do not need your pre-trained weights so far (it suffices to use other pre-trained weights, or even other much smaller backbone).

**Comment by yezhengli-Mr9** [comment]
By the code in [airsplay/py-bottom-up-attention#6](https://github.com/airsplay/py-bottom-up-attention/issues/6) which originates from 
(1) [detectron2_mscoco_proposal_maxnms.py](https://github.com/airsplay/py-bottom-up-attention/blob/master/demo/detectron2_mscoco_proposal_maxnms.py) (which I frequently mentioned in #7 and [LXMERT#48](https://github.com/airsplay/lxmert/issues/48)) and 
(2) also checked [extract_nlvr2_image.py in LXMERT](https://github.com/airsplay/lxmert/blob/master/data/nlvr2_imgfeat/extract_nlvr2_image.py)(since I successfully run though a cpu-only version [here](https://github.com/airsplay/lxmert/issues/89))
It is estimated to finish extracting features of 1,102,076+ personal images within 57-44 hours (with 1 or 4 GPUs), which is consistent with speed of extracting features in [LXMERT](https://github.com/airsplay/lxmert), that is, 5-6 hours for 107,292 images in NLVR2 (but there it uses merely [one GPU](https://github.com/airsplay/lxmert/issues/48)).

**Comment by yikuan8** [comment]
@yezhengli-Mr9 Glad you nail it. Please let me know if you need further help.

**Comment by o0t1ng0o** [comment]
> By the code in [airsplay/py-bottom-up-attention#6](https://github.com/airsplay/py-bottom-up-attention/issues/6) which originates from (1) [detectron2_mscoco_proposal_maxnms.py](https://github.com/airsplay/py-bottom-up-attention/blob/master/demo/detectron2_mscoco_proposal_maxnms.py) (which I frequently mentioned in #7 and [LXMERT#48](https://github.com/airsplay/lxmert/issues/48)) and (2) also checked [extract_nlvr2_image.py in LXMERT](https://github.com/airsplay/lxmert/blob/master/data/nlvr2_imgfeat/extract_nlvr2_image.py)(since I successfully run though a cpu-only version [here](https://github.com/airsplay/lxmert/issues/89)) It is estimated to finish extracting features of 1,102,076+ personal images within 57-44 hours (with 1 or 4 GPUs), which is consistent with speed of extracting features in [LXMERT](https://github.com/airsplay/lxmert), that is, 5-6 hours for 107,292 images in NLVR2 (but there it uses merely [one GPU](https://github.com/airsplay/lxmert/issues/48)).

Hi @yezhengli-Mr9 ,
Can you share the code how you speed up the process of extracting features?
